name: pre-commit

# Controls when the workflow will run
on:
  pull_request:
    paths:
       - '.github/workflows/pre-commit.yml'
       - '.pre-commit-config.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Lint the repository with pre-commit
        run: |
          python3 -V
          pip3 install --upgrade pip
          pip3 install pre-commit==2.19.0
          pre-commit run --verbose
